import { StyleSheet } from "react-native";

const addAlarmStyles = StyleSheet.create({
  container: {
    backgroundColor: "#404040",
    width: "100%",
    flex: 1,
    justifyContent: "top",
    alignItems: "center",
    paddingTop: 20,
    gap: 10,
  },
  titleAddText: {
    width: "80%",
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    marginTop: 20,
  },
  pickerContainer: {
    width: 300,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
    borderBottomColor: "#ffffff",
    borderBottomWidth: 1,
    borderTopColor: "#ffffff",
    borderTopWidth: 1,
  },
  picker: {
    height: 200,
    width: 100,
    overflow: "hidden",
    borderRadius: 12,
  },
  amPmPicker: {
    height: 200,
    width: 100,
    overflow: "hidden",
    borderRadius: 12,
    marginRight: -20,
  },
  item: {
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  timeStamp: {
    marginBottom: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonContainer: {
    flex: 0,
    width: "80%",
  },
  buttonBox: {
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#909090",
    borderRadius: 10,
  },
  button: {
    flex: 0,
    flexDirection: "row",
    width: "95%",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  buttonBorder: {
    width: "95%",
    flex: 0,
    textAlign: "center",
    borderBottomColor: "#ffffff",
    borderBottomWidth: 1,
  },
  saveButtonContainer: {
    height: "58%",
    flex: 0,
    justifyContent: "flex-end",
  },
});

const alarmListStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#404040",
    gap: 2,
  },
  headerContainer: {
    marginTop: 20,
    marginLeft: 40,
    marginRight: 40,
  },
  alarmListBox: {
    width: 340,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    pointerEvents: "auto",
  },
  alarmListTitleBox: {
    width: "100%",
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    position: "absolute",
    left: 0,
    right: 0,
    top: 10,
  },
  alarmListTitle: {
    width: 320,
    fontSize: 35,
    borderTopWidth: 3,
    borderColor: "#ffffff",
    padding: 10,
    textAlign: "center",
  },
  buttonBox: {
    height: 90,
    borderRadius: 10,
    shadowColor: "#242424",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    marginBottom: 10,
    padding: 10,
  },
  slectedTimeBox: {
    width: "70%",
    flex: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginLeft: 5,
    marginTop: 2,
  },
  dayItemsBox: {
    flex: 0.5,
    flexDirection: "row",
    gap: 7,
    marginLeft: 10,
  },
  addButton: {
    zIndex: 10,
    width: 10,
    height: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  addButtonImg: {
    width: 60,
    height: 60,
    resizeMode: "contain",
    position: "absolute",
    flex: 0.1,
    left: 110,
    bottom: -50,
  },
});

const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#404040",
    gap: 20,
  },
  icon: {
    resizeMode: "center",
    width: 150,
    height: 150,
    marginBottom: 5,
  },
  loginButtonWarpper: {
    width: 300,
  },
  button: {
    padding: 10,
    flex: 0,
    width: "100%",
    height: 55,
    borderRadius: 50,
    backgroundColor: "#ffffff",
    gap: 10,
  },
  buttonInnerBox: {
    flex: 1,
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  buttonInnerLogo: {
    flex: 1,
    resizeMode: "center",
    width: 30,
    height: 30,
  },
  buttonInnerText: {
    fontSize: 21,
  },
});

const actionAlarmStyles = StyleSheet.create({
  container: {
    flex: 3,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "#404040",
    paddingTop: 30,
    paddingBottom: 30,
  },
  topBox: {
    flex: 0,
    width: 400,
    height: 150,
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  currentTimeBox: {
    flex: 0,
    marginTop: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  quizTextContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: 370,
    height: 100,
    gap: 15,
  },
  fileRootText: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: -12,
    marginTop: -10,
    marginBottom: 10,
  },
  quizTextBox: {
    minWidth: 370,
    maxWidth: 385,
    minHeight: 330,
    maxHeight: 350,
    borderWidth: 2,
    backgroundColor: "#282C35",
    padding: 20,
    borderRadius: 15,
  },
  rootText: {
    minWidth: 300,
    maxWidth: 320,
    color: "#C0C0C0",
    fontSize: 10,
  },
  quizText: {
    color: "#ffffff",
  },
  textInput: {
    backgroundColor: "#ffffff",
    textAlign: "center",
    width: 350,
    height: 50,
    borderRadius: 10,
    fontSize: 12.5,
  },
  buttonInnerBox: {
    flex: 1,
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  button: {
    width: "85%",
    height: 55,
    borderRadius: 50,
    backgroundColor: "#ffffff",
  },
});

export { addAlarmStyles, alarmListStyles, loginStyles, actionAlarmStyles };
